// mobile/src/views/Chat.vue
<template>
  <div class="chat-page">
    <!-- 聊天头部 -->
    <div class="chat-header">
      <van-icon name="chat-o" size="20" color="#1989fa" />
      <span class="chat-title">AI 助手</span>
      <!-- 状态指示灯 -->
      <span
        :class="['status-dot', `status-${healthStatus}`]"
        :title="healthHint"
      />
      <van-tag plain color="#1989fa" size="small">DeepSeek Flash</van-tag>
      <van-tag v-if="lastCost" plain color="#07c160" size="small" style="margin-right:4px">
        ${{ lastCost.toFixed(6) }}
      </van-tag>
      <div style="margin-left: auto; display: flex; gap: 8px; align-items: center">
        <van-icon
          name="add-square"
          size="18"
          color="#666"
          title="新对话"
          @click="newChat"
        />
      </div>
    </div>

    <!-- 消息列表 -->
    <div class="chat-messages" ref="messagesRef">
      <!-- 空状态 -->
      <div v-if="messages.length === 0 && !streaming" class="chat-empty">
        <van-icon name="chat-o" size="48" color="#ccc" />
        <p style="color: #999; margin-top: 8px">
          AI 助手，查询数据、分析、写代码
        </p>
        <p style="color: #bbb; margin-top: 4px; font-size: 12px">
          支持上传 txt / py / pdf / docx / xlsx 等文件
        </p>
        <van-space direction="vertical" :size="8" style="width: 80%">
          <van-button
            v-for="(q, i) in exampleQuestions"
            :key="i"
            plain
            hairline
            round
            size="small"
            color="#1989fa"
            @click="sendMessage(q)"
          >
            {{ q }}
          </van-button>
        </van-space>
      </div>

      <!-- 消息气泡 -->
      <div
        v-for="(msg, i) in messages"
        :key="i"
        :class="['msg-row', msg.role === 'user' ? 'msg-user' : 'msg-ai']"
      >
        <div class="msg-label">
          <van-icon :name="msg.role === 'user' ? 'contact' : 'chat'" />
          {{ msg.role === 'user' ? '你' : 'AI' }}
        </div>
        <!-- 用户消息中的文件信息 -->
        <div v-if="msg.files && msg.files.length > 0" style="margin-bottom:6px;font-size:12px;display:flex;flex-wrap:wrap;gap:4px">
          <van-tag v-for="(f, fi) in msg.files" :key="fi" plain size="small">
            📄 {{ f.name }}
          </van-tag>
        </div>
        <div class="msg-bubble" v-html="renderContent(msg.content)" />
        <!-- 变更文件下载 -->
        <div v-if="msg.changed_files && msg.changed_files.length > 0" class="msg-download">
          <div class="msg-download-title">📁 本次变更（{{ msg.changed_files.length }}个文件）</div>
          <div class="msg-download-files">
            <van-tag v-for="(f, fi) in msg.changed_files" :key="fi" plain size="small" style="margin:2px;max-width:240px;overflow:hidden;text-overflow:ellipsis">
              {{ f }}
            </van-tag>
          </div>
          <van-button
            size="small"
            plain
            type="primary"
            icon="down"
            @click="downloadFiles(msg.changed_files)"
          >
            打包下载
          </van-button>
        </div>
      </div>

      <!-- 流式输出 -->
      <div v-if="streaming" class="msg-row msg-ai">
        <div class="msg-label">
          <van-icon name="chat" />
          AI
          <van-loading type="ball" size="14" style="display: inline-block; margin-left: 4px" />
        </div>
        <div class="msg-bubble" v-html="renderContent(streaming)" />
      </div>

      <div ref="scrollEnd" />
    </div>

    <!-- 输入区域 -->
    <div class="chat-input">
      <!-- 已上传文件列表 -->
      <div v-if="uploadedFiles.length > 0" class="chat-file-list">
        <div v-for="(f, i) in uploadedFiles" :key="f.file_id" class="chat-file-tag">
          <span>📄 {{ f.name }}</span>
          <van-icon name="close" size="14" @click="removeFile(i)" style="margin-left:4px;flex-shrink:0" />
        </div>
      </div>

      <div class="chat-input-row">
        <!-- 文件上传按钮 -->
        <van-icon
          name="add-o"
          size="22"
          color="#1989fa"
          class="chat-upload-btn"
          :class="{ disabled: loading || uploading }"
          @click="triggerFileUpload"
        />
        <input
          ref="fileInputRef"
          type="file"
          multiple
          style="display:none"
          @change="onFileSelect"
          accept=".txt,.py,.js,.ts,.vue,.css,.html,.json,.yaml,.yml,.md,.csv,.xml,.sql,.sh,.toml,.ini,.cfg,.log,.env,.pdf,.docx,.xlsx,.xls,.go,.rs,.java,.c,.cpp,.h,.hpp,.rb,.php,.kt,.gradle,.proto,.graphql"
        />

        <van-field
          v-model="input"
          type="textarea"
          :autosize="{ minHeight: 44, maxHeight: 100 }"
          :placeholder="uploadedFiles.length > 0 ? '输入关于这些文件的问题...' : '输入你的问题...'"
          :disabled="loading || uploading"
          @keypress.enter.exact.prevent="sendMessage(input)"
        >
          <template #button>
            <van-button
              :icon="loading ? 'loading' : 'send'"
              :disabled="loading || uploading || !input.trim()"
              color="#1989fa"
              size="small"
              round
              @click="sendMessage(input)"
            />
          </template>
        </van-field>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, nextTick, watch, onMounted, onUnmounted } from 'vue'
import { showToast, showConfirmDialog } from 'vant'
import { useRouter } from 'vue-router'

const router = useRouter()
const input = ref('')
const messages = ref([])
const streaming = ref('')
const loading = ref(false)
const lastCost = ref(0)
const uploadedFiles = ref([])
const uploading = ref(false)
const messagesRef = ref(null)
const scrollEnd = ref(null)
const fileInputRef = ref(null)

// ── 状态指示 ──
const healthStatus = ref('checking') // 'checking' | 'ok' | 'degraded' | 'down'
const healthHint = ref('检查中...')
let healthTimer = null

// ── 持久化 Key ──
const STORAGE_KEY = 'hermes_chat_messages'
const HEALTH_POLL_MS = 15000  // 15秒轮询

const BASE_URL = ''

const exampleQuestions = [
  '帮我看看今天消耗了多少Token',
  '列出所有用户信息',
  '最近的充值订单有哪些',
  '帮我写一个分析SQL',
]

function getToken() {
  return localStorage.getItem('token') || ''
}

// ── 健康检查 ──
async function checkHealth() {
  const token = getToken()
  if (!token) {
    healthStatus.value = 'down'
    healthHint.value = '未登录'
    return
  }
  try {
    const res = await fetch(`${BASE_URL}/api/chat/health`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const data = await res.json()
    if (data.status === 'ok') {
      healthStatus.value = 'ok'
      healthHint.value = 'AI 助手在线'
    } else {
      healthStatus.value = 'degraded'
      healthHint.value = 'AI 助手异常: ' + (data.error || '')
    }
  } catch {
    healthStatus.value = 'down'
    healthHint.value = '后台不可用'
  }
}

function startHealthPoll() {
  checkHealth()
  healthTimer = setInterval(checkHealth, HEALTH_POLL_MS)
}

function stopHealthPoll() {
  if (healthTimer) {
    clearInterval(healthTimer)
    healthTimer = null
  }
}

// ── localStorage 持久化 ──
function loadFromStorage() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const parsed = JSON.parse(raw)
      if (Array.isArray(parsed)) {
        messages.value = parsed
      }
    }
  } catch {
    // ignore
  }
}

function saveToStorage() {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(messages.value))
  } catch {
    // localStorage 满时忽略
  }
}

// ── 后端同步 ──
let saveDebounceTimer = null

function syncToBackend() {
  if (saveDebounceTimer) clearTimeout(saveDebounceTimer)
  saveDebounceTimer = setTimeout(async () => {
    const token = getToken()
    if (!token || messages.value.length === 0) return
    try {
      await fetch(`${BASE_URL}/api/chat/history`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify({ messages: messages.value }),
      })
    } catch {
      // 后端同步失败不影响前端使用
    }
  }, 1000)
}

async function loadFromBackend() {
  const token = getToken()
  if (!token) return
  try {
    const res = await fetch(`${BASE_URL}/api/chat/history`, {
      headers: { 'Authorization': `Bearer ${token}` },
    })
    if (!res.ok) return
    const data = await res.json()
    if (data.messages && data.messages.length > 0) {
      // 以后端数据为准，覆盖 localStorage
      messages.value = data.messages
      saveToStorage()
    }
  } catch {
    // ignore — localStorage 兜底
  }
}

// ── 生命周期 ──
onMounted(async () => {
  // 1) 快速从 localStorage 恢复（即时显示）
  loadFromStorage()
  // 2) 从后端同步（覆盖更新）
  await loadFromBackend()
  // 3) 开始健康检查
  startHealthPoll()
})

onUnmounted(() => {
  stopHealthPoll()
  if (saveDebounceTimer) clearTimeout(saveDebounceTimer)
  // 离开时保存
  saveToStorage()
})

// 消息变化时自动保存
watch(messages, () => {
  saveToStorage()
  syncToBackend()
}, { deep: true })

function renderContent(text) {
  if (!text) return ''
  let html = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/```(\w*)\n?([\s\S]*?)```/g, '<pre style="background:#f5f5f5;padding:8px;border-radius:6px;overflow-x:auto;font-size:12px;margin:4px 0"><code>$2</code></pre>')
    .replace(/`([^`]+)`/g, '<code style="background:#f0f0f0;padding:1px 4px;border-radius:3px;font-size:12px">$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\n/g, '<br>')
  return html
}

function scrollToBottom() {
  nextTick(() => {
    scrollEnd.value?.scrollIntoView({ behavior: 'smooth' })
  })
}

watch([messages, streaming], scrollToBottom)

function triggerFileUpload() {
  if (loading.value || uploading.value) return
  fileInputRef.value?.click()
}

async function onFileSelect(e) {
  const files = e.target.files
  if (!files || files.length === 0) return

  uploading.value = true
  const token = getToken()

  for (const file of files) {
    const formData = new FormData()
    formData.append('file', file)

    try {
      const res = await fetch(`${BASE_URL}/api/chat/upload`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${token}` },
        body: formData,
      })
      if (!res.ok) {
        const err = await res.json()
        showToast(err.detail || '上传失败')
        continue
      }
      const data = await res.json()
      uploadedFiles.value.push({
        file_id: data.file_id,
        name: data.name,
        type: data.type,
        size: data.size,
      })
      showToast(`✅ ${data.name}`)
    } catch (err) {
      showToast(err.message)
    }
  }
  uploading.value = false
  e.target.value = ''
}

function removeFile(index) {
  uploadedFiles.value.splice(index, 1)
}

function fmtSize(bytes) {
  if (bytes < 1024) return `${bytes}B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`
  return `${(bytes / 1024 / 1024).toFixed(1)}MB`
}

function newChat() {
  showConfirmDialog({
    title: '新对话',
    message: '清空当前对话并开始新对话？历史记录已自动保存。',
    confirmButtonText: '确定',
    cancelButtonText: '取消',
  }).then(() => {
    messages.value = []
    streaming.value = ''
    lastCost.value = 0
    input.value = ''
    uploadedFiles.value = []
    saveToStorage()
    syncToBackend()
  }).catch(() => {
    // 取消
  })
}

/** 下载变更文件 */
async function downloadFiles(files) {
  const token = getToken()
  if (!token || !files?.length) return
  try {
    const res = await fetch(`${BASE_URL}/api/chat/download`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
      body: JSON.stringify({ files }),
    })
    if (!res.ok) { showToast('下载失败'); return }
    const blob = await res.blob()
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `claude-output-${Date.now()}.zip`
    a.click()
    URL.revokeObjectURL(url)
    showToast(`✅ 已下载 ${files.length} 个文件`)
  } catch (err) {
    showToast(`下载失败: ${err.message}`)
  }
}

async function sendMessage(text) {
  if (!text?.trim() || loading.value) return
  const msgText = text
  input.value = ''
  loading.value = true
  streaming.value = ''
  lastCost.value = 0

  const files = [...uploadedFiles.value]
  messages.value.push({ role: 'user', content: msgText, files })

  const history = messages.value
    .filter(m => m.content !== msgText)
    .map(m => ({ role: m.role, content: m.content }))

  try {
    const token = getToken()
    const body = { message: msgText, history }
    if (files.length > 0) {
      body.files = files.map(f => ({ file_id: f.file_id, name: f.name }))
    }

    const res = await fetch(`${BASE_URL}/api/chat/stream`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
      },
      body: JSON.stringify(body),
    })

    if (!res.ok) {
      throw new Error(`HTTP ${res.status}`)
    }

    const reader = res.body.getReader()
    const decoder = new TextDecoder()
    let fullText = ''
    let buffer = ''

    while (true) {
      const { done, value } = await reader.read()
      if (done) break

      buffer += decoder.decode(value, { stream: true })
      const lines = buffer.split('\n')
      buffer = lines.pop() || ''

      for (const line of lines) {
        const trimmed = line.trim()
        if (!trimmed.startsWith('data: ')) continue
        try {
          const data = JSON.parse(trimmed.slice(6))
          switch (data.type) {
            case 'text':
              fullText += data.content
              streaming.value = fullText
              break
            case 'tool_use': {
              const cmd = data.input?.command || ''
              const label = cmd ? `$ ${cmd}` : `[使用工具: ${data.name}]`
              fullText += `\n\n🔧 ${label}\n`
              streaming.value = fullText
              break
            }
            case 'tool_result': {
              const icon = data.is_error ? '❌' : '📋'
              const lines = (data.content || '').split('\n')
              const preview = lines.length > 6
                ? lines.slice(0, 6).join('\n') + `\n... (${lines.length} lines)`
                : data.content
              const cmdLine = data.command ? `$ ${data.command}` : ''
              fullText += `\n${icon} ${cmdLine || data.tool_name}\n\`\`\`\n${preview}\n\`\`\`\n`
              streaming.value = fullText
              break
            }
            case 'done':
              lastCost.value = data.cost || 0
              const aiMsg = { role: 'assistant', content: data.content }
              if (data.changed_files?.length > 0) {
                aiMsg.changed_files = data.changed_files
              }
              messages.value.push(aiMsg)
              streaming.value = ''
              break
            case 'error':
              streaming.value = (streaming.value || '') + `\n\n⚠️ ${data.message}`
              break
          }
        } catch (e) {
          // ignore
        }
      }
    }
  } catch (err) {
    showToast(err.message)
  } finally {
    loading.value = false
    streaming.value = ''
  }
}
</script>

<style scoped>
.chat-page {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: #f7f8fa;
}

.chat-header {
  display: flex;
  align-items: center;
  padding: 12px 16px;
  background: #fff;
  border-bottom: 1px solid #eee;
  gap: 8px;
  flex-shrink: 0;
}

.chat-title {
  font-size: 16px;
  font-weight: 600;
}

.chat-messages {
  flex: 1;
  overflow-y: auto;
  padding: 12px 16px;
  -webkit-overflow-scrolling: touch;
}

.chat-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 60vh;
  padding: 20px;
  text-align: center;
}

.msg-row {
  margin-bottom: 16px;
}

.msg-user {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}

.msg-ai {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
}

.msg-label {
  font-size: 12px;
  color: #999;
  margin-bottom: 4px;
  display: flex;
  align-items: center;
  gap: 4px;
}

.msg-bubble {
  max-width: 85%;
  padding: 10px 14px;
  border-radius: 12px;
  font-size: 14px;
  line-height: 1.6;
  word-break: break-word;
  white-space: pre-wrap;
}

.msg-user .msg-bubble {
  background: #1989fa;
  color: #fff;
  border-bottom-right-radius: 4px;
}

.msg-ai .msg-bubble {
  background: #fff;
  color: #333;
  border-bottom-left-radius: 4px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}

.msg-download {
  margin-top: 8px;
  padding-top: 8px;
  border-top: 1px solid #eee;
}
.msg-download-title {
  font-size: 11px;
  color: #666;
  margin-bottom: 4px;
}
.msg-download-files {
  display: flex;
  flex-wrap: wrap;
  gap: 2px;
  margin-bottom: 6px;
}

.chat-input {
  background: #fff;
  border-top: 1px solid #eee;
  flex-shrink: 0;
}

.chat-file-list {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  padding: 8px 12px 0;
}

.chat-file-tag {
  display: inline-flex;
  align-items: center;
  background: #e8f4fd;
  border: 1px solid #b3d8f0;
  border-radius: 16px;
  padding: 3px 8px;
  font-size: 12px;
  color: #1989fa;
  gap: 2px;
}

.chat-input-row {
  display: flex;
  align-items: flex-end;
  padding: 8px 12px;
  gap: 8px;
}

.chat-upload-btn {
  margin-bottom: 8px;
  cursor: pointer;
  flex-shrink: 0;
}

.chat-upload-btn.disabled {
  opacity: 0.4;
  cursor: not-allowed;
}

.chat-input-row :deep(.van-field) {
  flex: 1;
  padding: 0;
}

/* 状态指示灯 */
.status-dot {
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  flex-shrink: 0;
  transition: background 0.3s;
}
.status-checking {
  background: #ff9800;
  animation: pulse 1s infinite;
}
.status-ok {
  background: #07c160;
}
.status-degraded {
  background: #ff9800;
}
.status-down {
  background: #ee0a24;
}
@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}
</style>

// admin/src/pages/Chat.jsx
import React, { useState, useRef, useEffect, useCallback } from 'react'
import {
  Card, Input, Button, Typography, Space, Spin, Tooltip,
  Tag, Alert, Collapse, Divider, Upload, message,
} from 'antd'
import {
  SendOutlined, RobotOutlined, UserOutlined,
  DeleteOutlined, ClearOutlined, DollarOutlined,
  ClockCircleOutlined, PaperClipOutlined, FileTextOutlined,
  DownloadOutlined, CloseOutlined,
} from '@ant-design/icons'
import api from '../api'

const { Text, Paragraph } = Typography
const { TextArea } = Input

function getToken() {
  return localStorage.getItem('admin_token') || ''
}

const exampleQuestions = [
  '帮我看看今天消耗了多少Token',
  '列出所有用户信息',
  '最近的充值订单有哪些',
  '帮我写一个分析SQL',
]

/** 文件类型图标 */
function FileIcon({ type }) {
  const colorMap = {
    pdf: '#f40',
    docx: '#2b5797',
    excel: '#217346',
    text: '#1677ff',
    code: '#1677ff',
    image: '#722ed1',
  }
  return (
    <FileTextOutlined style={{ color: colorMap[type] || '#999', marginRight: 4 }} />
  )
}

export default function Chat() {
  const [messages, setMessages] = useState([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [streamingText, setStreamingText] = useState('')
  const [currentCost, setCurrentCost] = useState(null)
  const [uploadedFiles, setUploadedFiles] = useState([])
  const [uploading, setUploading] = useState(false)
  const [healthStatus, setHealthStatus] = useState('checking')
  const messagesEndRef = useRef(null)
  const fileInputRef = useRef(null)

  const STORAGE_KEY = 'admin_chat_messages'
  const saveTimerRef = useRef(null)

  /** 从 localStorage 加载 */
  const loadFromStorage = useCallback(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY)
      if (raw) {
        const parsed = JSON.parse(raw)
        if (Array.isArray(parsed)) setMessages(parsed)
      }
    } catch {}
  }, [])

  /** 保存到 localStorage */
  const saveToStorage = useCallback((msgs) => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(msgs))
    } catch {}
  }, [])

  /** 同步到后端（防抖） */
  const syncToBackend = useCallback((msgs) => {
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current)
    saveTimerRef.current = setTimeout(() => {
      const token = getToken()
      if (!token || msgs.length === 0) return
      fetch('/api/chat/history', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
        body: JSON.stringify({ messages: msgs }),
      }).catch(() => {})
    }, 1000)
  }, [])

  /** 消息变化时自动保存 */
  useEffect(() => {
    if (messages.length > 0) {
      saveToStorage(messages)
      syncToBackend(messages)
    }
  }, [messages, saveToStorage, syncToBackend])

  /** 加载历史 + 健康检查 */
  useEffect(() => {
    loadFromStorage()
    const token = getToken()
    if (token) {
      fetch('/api/chat/history', {
        headers: { 'Authorization': `Bearer ${token}` },
      }).then(r => r.json()).then(data => {
        if (data.messages && data.messages.length > 0) {
          setMessages(data.messages)
          saveToStorage(data.messages)
        }
      }).catch(() => {})
      // 健康检查
      const check = () => {
        fetch('/api/chat/health', {
          headers: { 'Authorization': `Bearer ${token}` },
        }).then(r => r.json()).then(d => {
          setHealthStatus(d.status === 'ok' ? 'ok' : 'degraded')
        }).catch(() => setHealthStatus('down'))
      }
      check()
      const timer = setInterval(check, 15000)
      return () => clearInterval(timer)
    }
  }, [loadFromStorage])

  const scrollToBottom = useCallback(() => {
    setTimeout(() => {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
    }, 50)
  }, [])

  useEffect(() => {
    scrollToBottom()
  }, [messages, streamingText, scrollToBottom])

  /** 上传文件 */
  const handleFileSelect = async (e) => {
    const files = e.target.files
    if (!files || files.length === 0) return

    setUploading(true)
    const token = getToken()

    for (const file of files) {
      const formData = new FormData()
      formData.append('file', file)

      try {
        const res = await fetch('/api/chat/upload', {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${token}` },
          body: formData,
        })
        if (!res.ok) {
          const err = await res.json()
          message.error(`${file.name}: ${err.detail || '上传失败'}`)
          continue
        }
        const data = await res.json()
        setUploadedFiles(prev => [...prev, {
          file_id: data.file_id,
          name: data.name,
          type: data.type,
          size: data.size,
        }])
        message.success(`✅ ${file.name} 已上传`)
      } catch (err) {
        message.error(`${file.name}: ${err.message}`)
      }
    }
    setUploading(false)
    // 清空 input 以支持重复选择同名文件
    e.target.value = ''
  }

  /** 移除已上传的文件 */
  const removeFile = (fileId) => {
    setUploadedFiles(prev => prev.filter(f => f.file_id !== fileId))
  }

  const sendMessage = async (text) => {
    const msg = text || input
    if (!msg.trim() || loading) return

    setInput('')
    setLoading(true)
    setStreamingText('')
    setCurrentCost(null)

    const userMsg = { role: 'user', content: msg, files: [...uploadedFiles] }
    const updatedMessages = [...messages, userMsg]
    setMessages(updatedMessages)

    const history = messages.map(m => ({ role: m.role, content: m.content }))

    try {
      const token = getToken()
      const body = { message: msg, history }
      // 如果有上传的文件，带上
      if (uploadedFiles.length > 0) {
        body.files = uploadedFiles.map(f => ({ file_id: f.file_id, name: f.name }))
      }

      const response = await fetch('/api/chat/stream', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`,
        },
        body: JSON.stringify(body),
      })

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`)
      }

      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let fullText = ''
      let buffer = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break

        buffer += decoder.decode(value, { stream: true })
        const lines = buffer.split('\n')
        buffer = lines.pop() || ''

        for (const line of lines) {
          const trimmed = line.trim()
          if (!trimmed.startsWith('data: ')) continue
          try {
            const data = JSON.parse(trimmed.slice(6))

            switch (data.type) {
              case 'text':
                fullText += data.content
                setStreamingText(fullText)
                break
              case 'tool_use': {
                const cmd = data.input?.command || ''
                const label = cmd
                  ? `$ ${cmd}`
                  : `[使用工具: ${data.name}]`
                setStreamingText((prev) => prev + `\n\n🔧 ${label}\n`)
                break
              }
              case 'tool_result': {
                const icon = data.is_error ? '❌' : '📋'
                const lines = (data.content || '').split('\n')
                const preview = lines.length > 8
                  ? lines.slice(0, 8).join('\n') + `\n... (${lines.length} lines)`
                  : data.content
                const cmdLine = data.command ? `$ ${data.command}` : ''
                setStreamingText((prev) => prev + `\n${icon} ${cmdLine || data.tool_name}\n\`\`\`\n${preview}\n\`\`\`\n`)
                break
              }
              case 'done':
                setCurrentCost({
                  cost: data.cost,
                  tokensInput: data.tokens_input,
                  tokensOutput: data.tokens_output,
                  duration: data.duration_ms,
                })
                const assistantMsg = { role: 'assistant', content: data.content }
                if (data.changed_files?.length > 0) {
                  assistantMsg.changed_files = data.changed_files
                }
                setMessages((prev) => [...prev, assistantMsg])
                setStreamingText('')
                break
              case 'error':
                setStreamingText((prev) => prev + `\n\n⚠️ ${data.message}`)
                break
            }
          } catch (e) {
            // ignore parse errors
          }
        }
      }
    } catch (err) {
      setStreamingText(`\n\n❌ 请求失败: ${err.message}`)
    } finally {
      setLoading(false)
      setStreamingText('')
      // 发送完后不清除文件（用户可手动移除或继续提问）
      // setUploadedFiles([])
    }
  }

  const clearChat = () => {
    setMessages([])
    setStreamingText('')
    setCurrentCost(null)
    setUploadedFiles([])
    saveToStorage([])
  }

  /** 下载变更文件 */
  const downloadFiles = async (files) => {
    const token = getToken()
    if (!token || !files?.length) return
    try {
      const res = await fetch('/api/chat/download', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${token}` },
        body: JSON.stringify({ files }),
      })
      if (!res.ok) { message.error('下载失败'); return }
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `claude-output-${Date.now()}.zip`
      a.click()
      URL.revokeObjectURL(url)
      message.success(`已下载 ${files.length} 个文件`)
    } catch (err) {
      message.error(`下载失败: ${err.message}`)
    }
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      sendMessage()
    }
  }

  /** 格式化文件大小 */
  const fmtSize = (bytes) => {
    if (bytes < 1024) return `${bytes}B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`
    return `${(bytes / 1024 / 1024).toFixed(1)}MB`
  }

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: '0 4px' }}>
      {/* 头部 */}
      <Card size="small" style={{ marginBottom: 12 }}>
        <Space>
          <RobotOutlined style={{ fontSize: 20, color: '#1677ff' }} />
          <Text strong style={{ fontSize: 16 }}>Claude Code AI 助手</Text>
          <Tag color="blue">DeepSeek Flash</Tag>
          <Tag
            color={healthStatus === 'ok' ? 'green' : healthStatus === 'checking' ? 'orange' : 'red'}
            style={{ fontSize: 11 }}
          >
            {healthStatus === 'ok' ? '● 在线' : healthStatus === 'checking' ? '◌ 检查中' : '○ 离线'}
          </Tag>
          {currentCost && (
            <>
              <Tag icon={<DollarOutlined />} color="green">
                ${(currentCost.cost || 0).toFixed(6)}
              </Tag>
              <Tag icon={<ClockCircleOutlined />} color="default">
                {(currentCost.duration / 1000).toFixed(1)}s
              </Tag>
            </>
          )}
          <Button
            size="small"
            icon={<ClearOutlined />}
            onClick={clearChat}
            danger
          >
            清空
          </Button>
        </Space>
      </Card>

      {/* 消息区域 */}
      <div
        style={{
          height: 'calc(100vh - 340px)',
          minHeight: 400,
          overflowY: 'auto',
          padding: '12px 0',
          marginBottom: 12,
        }}
      >
        {messages.length === 0 && !loading && (
          <div style={{ textAlign: 'center', padding: '40px 20px', color: '#999' }}>
            <RobotOutlined style={{ fontSize: 48, marginBottom: 16 }} />
            <Paragraph type="secondary">
              我是 AI 助手，可以帮你查询数据、分析代码、写 SQL 等
            </Paragraph>
            <Paragraph type="secondary" style={{ fontSize: 13 }}>
              支持上传 txt / py / pdf / docx / xlsx / json / md 等文件
            </Paragraph>
            <Space wrap>
              {exampleQuestions.map((q, i) => (
                <Button
                  key={i}
                  type="dashed"
                  size="small"
                  onClick={() => sendMessage(q)}
                >
                  {q}
                </Button>
              ))}
            </Space>
          </div>
        )}

        {/* 消息列表 */}
        {messages.map((msg, i) => (
          <div
            key={i}
            style={{
              display: 'flex',
              justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start',
              marginBottom: 16,
            }}
          >
            <div
              style={{
                maxWidth: '80%',
                padding: '10px 14px',
                borderRadius: 12,
                background: msg.role === 'user' ? '#1677ff' : '#f5f5f5',
                color: msg.role === 'user' ? '#fff' : '#333',
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-word',
              }}
            >
              <div style={{ marginBottom: 4, fontSize: 12, opacity: 0.7 }}>
                {msg.role === 'user' ? <UserOutlined /> : <RobotOutlined />}
                <span style={{ marginLeft: 4 }}>
                  {msg.role === 'user' ? '你' : 'AI'}
                </span>
              </div>
              {/* 显示用户消息中的文件信息 */}
              {msg.files && msg.files.length > 0 && (
                <div style={{ marginBottom: 6, fontSize: 12, opacity: 0.8 }}>
                  {msg.files.map((f, fi) => (
                    <Tag key={fi} style={{ marginBottom: 2 }}>
                      <FileIcon type={f.type} /> {f.name}
                    </Tag>
                  ))}
                </div>
              )}
              <div>{msg.content}</div>
              {/* 变更文件下载 */}
              {msg.changed_files && msg.changed_files.length > 0 && (
                <div style={{ marginTop: 8, borderTop: '1px solid #e8e8e8', paddingTop: 8 }}>
                  <div style={{ fontSize: 12, color: '#666', marginBottom: 4 }}>
                    📁 本次变更文件（{msg.changed_files.length}个）
                  </div>
                  <Space wrap size={2}>
                    {msg.changed_files.map((f, fi) => (
                      <Tag key={fi} style={{ fontSize: 11, maxWidth: 200 }}>{f}</Tag>
                    ))}
                  </Space>
                  <div style={{ marginTop: 6 }}>
                    <Button
                      size="small"
                      icon={<DownloadOutlined />}
                      type="primary"
                      ghost
                      onClick={() => downloadFiles(msg.changed_files)}
                    >
                      打包下载所有文件
                    </Button>
                  </div>
                </div>
              )}
            </div>
          </div>
        ))}

        {/* 流式输出 */}
        {streamingText && (
          <div
            style={{
              display: 'flex',
              justifyContent: 'flex-start',
              marginBottom: 16,
            }}
          >
            <div
              style={{
                maxWidth: '80%',
                padding: '10px 14px',
                borderRadius: 12,
                background: '#f5f5f5',
                color: '#333',
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-word',
              }}
            >
              <div style={{ marginBottom: 4, fontSize: 12, opacity: 0.7 }}>
                <RobotOutlined /> <Spin size="small" style={{ marginLeft: 4 }} /> AI 正在输入...
              </div>
              <div>{streamingText}</div>
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* 输入区域 */}
      <Card size="small">
        {/* 已上传文件列表 */}
        {uploadedFiles.length > 0 && (
          <div style={{ marginBottom: 8, display: 'flex', flexWrap: 'wrap', gap: 4 }}>
            {uploadedFiles.map((f) => (
              <Tag
                key={f.file_id}
                closable
                onClose={() => removeFile(f.file_id)}
                style={{ margin: 0 }}
              >
                <FileIcon type={f.type} />
                {f.name}
                <span style={{ marginLeft: 4, opacity: 0.6, fontSize: 11 }}>
                  {fmtSize(f.size)}
                </span>
              </Tag>
            ))}
          </div>
        )}

        <div style={{ display: 'flex', alignItems: 'flex-end', gap: 8 }}>
          {/* 附件按钮 */}
          <div>
            <input
              ref={fileInputRef}
              type="file"
              multiple
              style={{ display: 'none' }}
              onChange={handleFileSelect}
              accept=".txt,.py,.js,.ts,.jsx,.tsx,.vue,.css,.html,.json,.yaml,.yml,.md,.csv,.xml,.sql,.sh,.toml,.ini,.cfg,.conf,.log,.env,.pdf,.docx,.xlsx,.xls,.go,.rs,.java,.c,.cpp,.h,.hpp,.rb,.php,.kt,.gradle,.proto,.graphql"
            />
            <Tooltip title="上传文件（txt/py/pdf/docx/xlsx 等）">
              <Button
                icon={uploading ? <Spin size="small" /> : <PaperClipOutlined />}
                onClick={() => fileInputRef.current?.click()}
                disabled={loading || uploading}
                size="large"
              />
            </Tooltip>
          </div>

          {/* 输入框 */}
          <TextArea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={uploadedFiles.length > 0 ? '输入关于这些文件的问题...' : '输入你的问题，按 Enter 发送...'}
            rows={2}
            disabled={loading}
            style={{ resize: 'none', flex: 1 }}
          />

          {/* 发送按钮 */}
          <Button
            type="primary"
            icon={<SendOutlined />}
            onClick={() => sendMessage()}
            loading={loading}
            style={{ height: 'auto' }}
          >
            发送
          </Button>
        </div>
      </Card>
    </div>
  )
}
