// mobile/src/views/Login.vue
<template>
  <div class="page">
    <div class="login-header">
      <h2>TokenManager</h2>
      <p>欢迎回来</p>
    </div>

    <!-- 登录/注册 标签切换 -->
    <van-tabs v-model:active="activeTab" color="#667eea" title-active-color="#667eea" class="auth-tabs">
      <van-tab title="登录" name="login">
        <van-form @submit="onLogin">
          <van-cell-group inset>
            <van-field
              v-model="email"
              name="email"
              label="邮箱"
              placeholder="请输入邮箱"
              :rules="[{ required: true, message: '请输入邮箱' }, { pattern: /@/, message: '邮箱格式不正确' }]"
            >
              <template #button>
                <van-button
                  size="small"
                  type="primary"
                  :disabled="!canSendCode"
                  :loading="sendingCode"
                  @click="onSendCode"
                >
                  {{ sendCodeText }}
                </van-button>
              </template>
            </van-field>
            <van-field
              v-model="code"
              type="text"
              name="code"
              label="验证码"
              placeholder="请输入6位验证码"
              maxlength="6"
              :rules="[{ required: true, message: '请输入验证码' }, { pattern: /^\d{6}$/, message: '请输入6位数字验证码' }]"
            />
          </van-cell-group>
          <div style="margin: 16px;">
            <van-button round block type="primary" native-type="submit" :loading="loading">
              登录
            </van-button>
          </div>
        </van-form>
      </van-tab>

      <van-tab title="注册" name="register">
        <van-form @submit="onRegister">
          <van-cell-group inset>
            <van-field
              v-model="regEmail"
              name="regEmail"
              label="邮箱"
              placeholder="请输入邮箱"
              :rules="[{ required: true, message: '请输入邮箱' }, { pattern: /@/, message: '邮箱格式不正确' }]"
            >
              <template #button>
                <van-button
                  size="small"
                  type="primary"
                  :disabled="!canRegSendCode"
                  :loading="regSendingCode"
                  @click="onRegSendCode"
                >
                  {{ regSendCodeText }}
                </van-button>
              </template>
            </van-field>
            <van-field
              v-model="regCode"
              type="text"
              name="regCode"
              label="验证码"
              placeholder="请输入6位验证码"
              maxlength="6"
              :rules="[{ required: true, message: '请输入验证码' }, { pattern: /^\d{6}$/, message: '请输入6位数字验证码' }]"
            />
            <van-field
              v-model="regNickname"
              name="regNickname"
              label="昵称"
              placeholder="请输入昵称（选填）"
            />
            <van-field
              v-model="regPassword"
              type="password"
              name="regPassword"
              label="密码"
              placeholder="请设置密码（至少6位）"
              :rules="[{ required: true, message: '请设置密码' }, { pattern: /^.{6,}$/, message: '密码至少6位' }]"
            />
          </van-cell-group>
          <div style="margin: 16px;">
            <van-button round block type="primary" native-type="submit" :loading="regLoading">
              注册
            </van-button>
          </div>
        </van-form>
      </van-tab>
    </van-tabs>
  </div>
</template>

<script setup>
import { ref, computed, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { showToast } from 'vant'
import api, { logAction } from '../utils/api.js'

const router = useRouter()

// 登录
const email = ref('')
const code = ref('')
const loading = ref(false)
const sendingCode = ref(false)
const countdown = ref(0)

// 注册
const regEmail = ref('')
const regCode = ref('')
const regNickname = ref('')
const regPassword = ref('')
const regLoading = ref(false)
const regSendingCode = ref(false)
const regCountdown = ref(0)

const activeTab = ref('login')

// 登录验证码
const canSendCode = computed(() => countdown.value <= 0 && email.value.includes('@'))
const sendCodeText = computed(() => {
  if (sendingCode.value) return '发送中...'
  if (countdown.value > 0) return `${countdown.value}s`
  return '获取验证码'
})

// 注册验证码
const canRegSendCode = computed(() => regCountdown.value <= 0 && regEmail.value.includes('@'))
const regSendCodeText = computed(() => {
  if (regSendingCode.value) return '发送中...'
  if (regCountdown.value > 0) return `${regCountdown.value}s`
  return '获取验证码'
})

let loginTimer = null
let regTimer = null

// ====== 登录 ======
async function onSendCode() {
  if (!canSendCode.value) return
  sendingCode.value = true
  try {
    const res = await api.post('/auth/send-code', { email: email.value })
    showToast(res.message || '验证码已发送')
    countdown.value = 60
    loginTimer = setInterval(() => {
      countdown.value--
      if (countdown.value <= 0) { clearInterval(loginTimer); loginTimer = null }
    }, 1000)
  } catch (e) {
    showToast(e.response?.data?.detail || '发送失败')
  } finally { sendingCode.value = false }
}

async function onLogin() {
  loading.value = true
  try {
    const res = await api.post('/auth/code-login', { email: email.value, code: code.value, remember_me: true })
    localStorage.setItem('token', res.access_token)
    localStorage.setItem('user', JSON.stringify(res.user))
    logAction('login', '/login', `用户登录成功: ${email.value}`)
    showToast('登录成功')
    router.push('/home')
  } catch (e) {
    logAction('login_failed', '/login', `登录失败: ${email.value} - ${e.response?.data?.detail || '未知错误'}`)
    showToast(e.response?.data?.detail || '登录失败')
  } finally { loading.value = false }
}

// ====== 注册 ======
async function onRegSendCode() {
  if (!canRegSendCode.value) return
  regSendingCode.value = true
  try {
    const res = await api.post('/auth/send-code', { email: regEmail.value })
    showToast(res.message || '验证码已发送')
    regCountdown.value = 60
    regTimer = setInterval(() => {
      regCountdown.value--
      if (regCountdown.value <= 0) { clearInterval(regTimer); regTimer = null }
    }, 1000)
  } catch (e) {
    showToast(e.response?.data?.detail || '发送失败')
  } finally { regSendingCode.value = false }
}

async function onRegister() {
  if (!regPassword.value || regPassword.value.length < 6) {
    showToast('密码至少6位')
    return
  }
  regLoading.value = true
  try {
    const body = {
      email: regEmail.value,
      code: regCode.value,
      password: regPassword.value,
    }
    if (regNickname.value) body.nickname = regNickname.value
    await api.post('/auth/register', body)
    showToast('注册成功，请登录')
    // 切回登录tab，填入邮箱
    email.value = regEmail.value
    activeTab.value = 'login'
  } catch (e) {
    showToast(e.response?.data?.detail || '注册失败')
  } finally { regLoading.value = false }
}

onUnmounted(() => {
  if (loginTimer) clearInterval(loginTimer)
  if (regTimer) clearInterval(regTimer)
})
</script>

<style scoped>
.page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding: 0 16px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-header {
  text-align: center;
  margin-bottom: 20px;
  color: #fff;
}
.login-header h2 {
  font-size: 28px;
  margin: 0;
  font-weight: 700;
}
.login-header p {
  font-size: 14px;
  margin: 8px 0 0;
  opacity: 0.8;
}

.auth-tabs {
  background: transparent;
}
.auth-tabs :deep(.van-tabs__wrap) {
  margin-bottom: 16px;
}
.auth-tabs :deep(.van-tab) {
  color: rgba(255,255,255,0.7);
}
.auth-tabs :deep(.van-tab--active) {
  color: #fff;
  font-weight: 600;
}
</style>

// admin/src/pages/Login.jsx
import React, { useState, useRef } from 'react'
import { Form, Input, Button, Card, message, Typography, Space, Alert, Tabs } from 'antd'
import { MailOutlined, SafetyCertificateOutlined, LockOutlined, UserOutlined, KeyOutlined } from '@ant-design/icons'
import api from '../api'

const { Title, Text } = Typography

function AdminLoginForm({ onSuccess }) {
  const [loading, setLoading] = useState(false)
  const [codeLoading, setCodeLoading] = useState(false)
  const [countdown, setCountdown] = useState(0)
  const [email, setEmail] = useState('')
  const timerRef = useRef(null)

  const startCountdown = () => {
    setCountdown(60)
    timerRef.current = setInterval(() => {
      setCountdown((prev) => {
        if (prev <= 1) { clearInterval(timerRef.current); return 0 }
        return prev - 1
      })
    }, 1000)
  }

  const handleSendCode = async () => {
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      message.warning('请输入正确的邮箱地址')
      return
    }
    setCodeLoading(true)
    try {
      const res = await api.post('/auth/admin/send-code', { email })
      message.success({ content: `验证码已发送到 ${email}`, duration: 3 })
      startCountdown()
    } catch (e) {
      const detail = e.response?.data?.detail || '发送失败'
      if (detail.includes('未注册')) {
        message.error('该邮箱未注册为管理员')
      } else {
        message.error(detail)
      }
    } finally { setCodeLoading(false) }
  }

  const onFinish = async (values) => {
    setLoading(true)
    try {
      const res = await api.post('/auth/admin/login', { email: values.email, code: values.code })
      if (res.user?.role !== 'admin') {
        message.error('非管理员账号无法登录')
        return
      }
      localStorage.setItem('admin_token', res.access_token)
      localStorage.setItem('admin_user', JSON.stringify(res.user))
      localStorage.setItem('admin_login_time', Date.now().toString())
      message.success({ content: '✅ 管理员登录成功', duration: 2 })
      onSuccess()
    } catch (e) {
      const detail = e.response?.data?.detail || '登录失败'
      if (detail.includes('过期')) {
        message.warning('验证码已过期，请重新获取')
      } else {
        message.error(detail)
      }
    } finally { setLoading(false) }
  }

  return (
    <Form onFinish={onFinish} size="large" layout="vertical" initialValues={{ email: '' }}>
      <Form.Item name="email" label="管理员邮箱"
        rules={[{ required: true, message: '请输入邮箱' }, { type: 'email', message: '邮箱格式不正确' }]}
      >
        <Input prefix={<MailOutlined style={{ color: '#bfbfbf' }} />}
          placeholder="请输入管理员邮箱"
          style={{ borderRadius: 8, height: 44 }}
          onChange={(e) => setEmail(e.target.value)}
        />
      </Form.Item>

      <Form.Item name="code" label="邮箱验证码"
        rules={[{ required: true, message: '请输入验证码' }, { len: 6, message: '验证码为6位数字' }]}
      >
        <div style={{ display: 'flex', gap: 8 }}>
          <Input prefix={<SafetyCertificateOutlined style={{ color: '#bfbfbf' }} />}
            placeholder="6位验证码" maxLength={6}
            style={{ borderRadius: 8, height: 44, flex: 1 }}
          />
          <Button onClick={handleSendCode} disabled={countdown > 0}
            loading={codeLoading}
            style={{ borderRadius: 8, height: 44, minWidth: 110,
              background: countdown > 0 ? '#f5f5f5' : 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
              border: 'none', color: countdown > 0 ? '#999' : '#fff', fontWeight: 500 }}
          >
            {countdown > 0 ? `${countdown}s` : '获取验证码'}
          </Button>
        </div>
      </Form.Item>

      <Form.Item style={{ marginBottom: 12 }}>
        <Button type="primary" htmlType="submit" block loading={loading}
          style={{ height: 44, borderRadius: 8,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            border: 'none', fontSize: 15, fontWeight: 500,
            boxShadow: '0 4px 12px rgba(102,126,234,0.4)' }}
        >登录</Button>
      </Form.Item>
    </Form>
  )
}

function UserLoginForm({ onSuccess }) {
  const [loading, setLoading] = useState(false)

  const onFinish = async (values) => {
    setLoading(true)
    try {
      const res = await api.post('/auth/login', { account: values.email, password: values.password })
      localStorage.setItem('token', res.access_token)
      localStorage.setItem('user', JSON.stringify(res.user))
      message.success({ content: '✅ 登录成功', duration: 2 })
      // 跳转到 /home (H5)
      window.location.href = '/#/home'
    } catch (e) {
      message.error(e.response?.data?.detail || '登录失败')
    } finally { setLoading(false) }
  }

  return (
    <Form onFinish={onFinish} size="large" layout="vertical">
      <Form.Item name="email" label="邮箱"
        rules={[{ required: true, message: '请输入邮箱' }, { type: 'email', message: '邮箱格式不正确' }]}
      >
        <Input prefix={<MailOutlined style={{ color: '#bfbfbf' }} />}
          placeholder="请输入邮箱" style={{ borderRadius: 8, height: 44 }}
        />
      </Form.Item>
      <Form.Item name="password" label="密码"
        rules={[{ required: true, message: '请输入密码' }]}
      >
        <Input.Password prefix={<LockOutlined style={{ color: '#bfbfbf' }} />}
          placeholder="请输入密码" style={{ borderRadius: 8, height: 44 }}
        />
      </Form.Item>
      <Form.Item style={{ marginBottom: 12 }}>
        <Button type="primary" htmlType="submit" block loading={loading}
          style={{ height: 44, borderRadius: 8,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            border: 'none', fontSize: 15, fontWeight: 500,
            boxShadow: '0 4px 12px rgba(102,126,234,0.4)' }}
        >登录</Button>
      </Form.Item>
    </Form>
  )
}

function UserRegisterForm() {
  const [loading, setLoading] = useState(false)
  const [codeLoading, setCodeLoading] = useState(false)
  const [countdown, setCountdown] = useState(0)
  const [email, setEmail] = useState('')
  const timerRef = useRef(null)

  const startCountdown = () => {
    setCountdown(60)
    timerRef.current = setInterval(() => {
      setCountdown((prev) => {
        if (prev <= 1) { clearInterval(timerRef.current); return 0 }
        return prev - 1
      })
    }, 1000)
  }

  const handleSendCode = async () => {
    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      message.warning('请输入正确的邮箱地址')
      return
    }
    setCodeLoading(true)
    try {
      await api.post('/auth/send-code', { email })
      message.success({ content: `验证码已发送到 ${email}`, duration: 3 })
      startCountdown()
    } catch (e) {
      message.error(e.response?.data?.detail || '发送失败')
    } finally { setCodeLoading(false) }
  }

  const onFinish = async (values) => {
    setLoading(true)
    try {
      await api.post('/auth/register', {
        email: values.email,
        code: values.code,
        nickname: values.nickname || '',
        password: values.password,
      })
      message.success({ content: '✅ 注册成功，请登录', duration: 3 })
    } catch (e) {
      message.error(e.response?.data?.detail || '注册失败')
    } finally { setLoading(false) }
  }

  return (
    <Form onFinish={onFinish} size="large" layout="vertical">
      <Form.Item name="email" label="邮箱"
        rules={[{ required: true, message: '请输入邮箱' }, { type: 'email', message: '邮箱格式不正确' }]}
      >
        <Input prefix={<MailOutlined style={{ color: '#bfbfbf' }} />}
          placeholder="请输入邮箱" style={{ borderRadius: 8, height: 44 }}
          onChange={(e) => setEmail(e.target.value)}
        />
      </Form.Item>

      <Form.Item name="code" label="验证码"
        rules={[{ required: true, message: '请输入验证码' }, { len: 6, message: '验证码为6位数字' }]}
      >
        <div style={{ display: 'flex', gap: 8 }}>
          <Input prefix={<SafetyCertificateOutlined style={{ color: '#bfbfbf' }} />}
            placeholder="6位验证码" maxLength={6}
            style={{ borderRadius: 8, height: 44, flex: 1 }}
          />
          <Button onClick={handleSendCode} disabled={countdown > 0}
            loading={codeLoading}
            style={{ borderRadius: 8, height: 44, minWidth: 110,
              background: countdown > 0 ? '#f5f5f5' : 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
              border: 'none', color: countdown > 0 ? '#999' : '#fff', fontWeight: 500 }}
          >
            {countdown > 0 ? `${countdown}s` : '获取验证码'}
          </Button>
        </div>
      </Form.Item>

      <Form.Item name="nickname" label="昵称">
        <Input prefix={<UserOutlined style={{ color: '#bfbfbf' }} />}
          placeholder="请输入昵称（选填）" style={{ borderRadius: 8, height: 44 }}
        />
      </Form.Item>

      <Form.Item name="password" label="密码"
        rules={[{ required: true, message: '请设置密码' }, { min: 6, message: '密码至少6位' }]}
      >
        <Input.Password prefix={<LockOutlined style={{ color: '#bfbfbf' }} />}
          placeholder="请设置密码（至少6位）" style={{ borderRadius: 8, height: 44 }}
        />
      </Form.Item>

      <Form.Item style={{ marginBottom: 12 }}>
        <Button type="primary" htmlType="submit" block loading={loading}
          style={{ height: 44, borderRadius: 8,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            border: 'none', fontSize: 15, fontWeight: 500,
            boxShadow: '0 4px 12px rgba(102,126,234,0.4)' }}
        >注册</Button>
      </Form.Item>
    </Form>
  )
}

export default function Login({ onLogin }) {
  return (
    <div style={{
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(135deg, #0c0c2e 0%, #1a1a4e 30%, #2d1b69 60%, #667eea 100%)',
      position: 'relative',
      overflow: 'hidden',
    }}>
      {/* 装饰性背景圆 */}
      <div style={{
        position: 'absolute', top: '-20%', right: '-10%',
        width: 500, height: 500, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(102,126,234,0.15) 0%, transparent 70%)',
        pointerEvents: 'none',
      }} />
      <div style={{
        position: 'absolute', bottom: '-15%', left: '-5%',
        width: 400, height: 400, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(118,75,162,0.2) 0%, transparent 70%)',
        pointerEvents: 'none',
      }} />

      <Card style={{
        width: 420, borderRadius: 16,
        boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
        border: '1px solid rgba(255,255,255,0.1)',
        background: 'rgba(255,255,255,0.98)',
        backdropFilter: 'blur(10px)',
        zIndex: 1,
      }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <div style={{
            width: 56, height: 56, borderRadius: 14,
            background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            margin: '0 auto 16px',
            fontSize: 28, color: '#fff',
            boxShadow: '0 4px 12px rgba(102,126,234,0.4)',
          }}>
            <KeyOutlined />
          </div>
          <Title level={3} style={{ margin: 0 }}>TokenManager</Title>
          <Text type="secondary">管理后台</Text>
        </div>

        <Tabs
          centered
          items={[
            {
              key: 'admin',
              label: '管理员登录',
              children: (
                <>
                  <AdminLoginForm onSuccess={onLogin} />
                  <Alert message="验证码将发送至您的管理员邮箱" type="info" showIcon
                    style={{ borderRadius: 8, fontSize: 12 }} />
                </>
              ),
            },
            {
              key: 'user',
              label: '用户登录',
              children: <UserLoginForm onSuccess={onLogin} />,
            },
            {
              key: 'register',
              label: '用户注册',
              children: (
                <>
                  <UserRegisterForm />
                  <Alert message="注册后可在用户登录页登录，管理员可在后台查看用户信息" type="info" showIcon
                    style={{ borderRadius: 8, fontSize: 12, marginTop: 8 }} />
                </>
              ),
            },
          ]}
        />
      </Card>
    </div>
  )
}
